include: ['assets/', 'CNAME']
exclude:
  - node_modules
  - Semantic-UI
  - src
  - .ruby-version
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - postcss.json
watch_exclude: ['dist/']
encoding: UTF-8

permalink: /:categories/:title

title: 有个想法
tagline: Site Tagline
production_url : https://www.yougexiangfa.com

navigation:
 - url: /
   title: 首页
 - url: /category
   title: 文章
 - url: /examples
   title: UI
 - url: /about
   title: 关于我们

lessc: 'date'
