include: ['assets/', 'CNAME']
exclude:
  - node_modules
  - Semantic-UI
  - src
  - .ruby-version
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - postcss.json
watch_exclude: ['dist/']
encoding: UTF-8

permalink: /:categories/:title

title: 一个想法
tagline: Site Tagline
production_url : http://www.xinshengyin.com

navigation:
 - url: /
   title: 组件
 - url: /examples/collections
   title: 集合
 - url: /examples/modules
   title: 模块
 - url: /examples/examples
   title: 示例

lessc: 'date'
