include: ['assets/', 'CNAME']
exclude: ['dist/', '.ruby-version', 'README.md', 'Rakefile', 'Gemfile', 'Gemfile.lock']
encoding: UTF-8

permalink: /:categories/:title

title: Whmall UI
tagline: Site Tagline
production_url : http://www.xinshengyin.com

navigation:
 - url: /
   title: 组件
 - url: /modules
   title: 模块
 - url: /examples
   title: 示例

lessc: 'lessc --clean-css src/whmall-css.less dist/whmall-ui.css'
